### ISSUE TITLE
demo_tp.py demo does not generate input.json, encoders.json

### ISSUE THREAD

**Issue by matejaputic** [numenta/nupic.cerebro2.server#16]
After having installed cerebro2 server and client, from the `nupic.cerebro2.server` directory, I run `demo/demo_tp.py`. 

Running `tree` on `/tmp/cerebro2/model` produces [this](http://pastebin.com/w2DfmuZQ). 

In a separate terminal I'm running the cerebro2 server with a browser open at `http://localhost:8000`

Next I run `server.py`, then reload the browser.

The cerebro2 client throws the following errors (full output [here](http://pastebin.com/NtMmZTZg)):

`IOError: [Errno 2] No such file or directory: u'/tmp/cerebro2/model/encoders.json'`
`IOError: [Errno 2] No such file or directory: u'/tmp/cerebro2/model/dimensions/input.json'`

I have tried stepping into the `Patcher().patchTP(tp)` call with a debugger, but it references code inside a python egg, so I am not able to browse the arguments passed to the internal `saveState` call without modification. Why wouldn't the patcher be generating `input.json` and `encoders.json` files?

**Comment by rhyolight** [comment]
@chetan51 Can you confirm validity of this issue?

**Comment by chetan51** [comment]
@matejaputic Do you still see a visualization in the browser? In this case, those errors that the webapp is printing might not actually be a problem. We might just need to suppress them when they're expected.

**Comment by matejaputic** [comment]
I got a little farther with this issue (pastebin [here](http://pastebin.com/dSZTMAfa)). The frontend is showing active cells and predicted cells. However, I don't understand why the backend sever output says `IOError: [Errno 2] No such file or directory: u'/tmp/cerebro2/model/states/1/input/active_cells.json'` and then on the next line it says `10.0.2.2:62234 - - [17/Mar/2015 12:25:33] "HTTP/1.1 GET /_model/states/1/output/active_cells" - 200 OK` (Lines 64 and 66 in the pastebin) How can that be? It might be a clue that they are being requested on two different ports.

Also, `active_columns` and `proximal_synapses` are missing, so there are no synapses in the output, which looks like this: 
![image](https://cloud.githubusercontent.com/assets/2180391/6692449/0b013554-cca3-11e4-8f53-07217ecbd729.png)

**Comment by chetan51** [comment]
Right, the TP demo doesn't export any proximal synapses information, so I think the client is requesting the information (by default) but suppressing the error. Not sure though.

**Comment by matejaputic** [comment]
OK it seems like this demo is working, then. Unless you think the errors should be suppressed server-side as well, I think we can close this. Thanks!
